feat(mise): reconfig and add gemini-cli, claude-code tools

diff --git a/zshrc-arch b/zshrc-arch
--- a/zshrc-arch
+++ b/zshrc-arch
@@ -55,58 +55,55 @@ export CLOUDSDK_PYTHON=$(which python3)
 export PICO_SDK_PATH="$HOME/Development/pico2w/pico-sdk"
 
 # === Start: Mise ===
-export MISE_SHELL=zsh
-export __MISE_ORIG_PATH="$PATH"
+#compdef mise
+local curcontext="$curcontext"
 
-mise() {
-  local command
-  command="${1:-}"
-  if [ "$#" = 0 ]; then
-    command mise
-    return
+# caching config
+_usage_mise_cache_policy() {
+  if [[ -z "${lifetime}" ]]; then
+    lifetime=$((60*60*4)) # 4 hours
   fi
-  shift
-
-  case "$command" in
-  deactivate|s|shell)
-    # if argv doesn't contains -h,--help
-    if [[ ! " $@ " =~ " --help " ]] && [[ ! " $@ " =~ " -h " ]]; then
-      eval "$(command mise "$command" "$@")"
-      return $?
-    fi
-    ;;
-  esac
-  command mise "$command" "$@"
+  local -a oldp
+  oldp=( "$1"(Nms+${lifetime}) )
+  (( $#oldp ))
 }
 
-_mise_hook() {
-  eval "$(mise hook-env -s zsh)";
+_mise() {
+  typeset -A opt_args
+  local curcontext="$curcontext" spec cache_policy
+
+  if ! command -v usage &> /dev/null; then
+      echo >&2
+      echo "Error: usage CLI not found. This is required for completions to work in mise." >&2
+      echo "See https://usage.jdx.dev for more information." >&2
+      return 1
+  fi
+
+  zstyle -s ":completion:${curcontext}:" cache-policy cache_policy
+  if [[ -z $cache_policy ]]; then
+    zstyle ":completion:${curcontext}:" cache-policy _usage_mise_cache_policy
+  fi
+
+  if ( [[ -z "${_usage_spec_mise_2025_9_7:-}" ]] || _cache_invalid _usage_spec_mise_2025_9_7 ) \
+      && ! _retrieve_cache _usage_spec_mise_2025_9_7;
+  then
+    spec="$(mise usage)"
+    _store_cache _usage_spec_mise_2025_9_7 spec
+  fi
+
+  _arguments "*: :(($(usage complete-word --shell zsh -s "$spec" -- "${words[@]}" )))"
+  return 0
 }
-typeset -ag precmd_functions;
-if [[ -z "${precmd_functions[(r)_mise_hook]+1}" ]]; then
-  precmd_functions=( _mise_hook ${precmd_functions[@]} )
-fi
-typeset -ag chpwd_functions;
-if [[ -z "${chpwd_functions[(r)_mise_hook]+1}" ]]; then
-  chpwd_functions=( _mise_hook ${chpwd_functions[@]} )
+
+if [ "$funcstack[1]" = "_mise" ]; then
+    _mise "$@"
+else
+    compdef _mise mise
 fi
 
-if [ -z "${_mise_cmd_not_found:-}" ]; then
-    _mise_cmd_not_found=1
-    [ -n "$(declare -f command_not_found_handler)" ] && eval "${$(declare -f command_not_found_handler)/command_not_found_handler/_command_not_found_handler}"
+eval "$(mise activate zsh)"
 
-    function command_not_found_handler() {
-        if mise hook-not-found -s zsh -- "$1"; then
-          _mise_hook
-          "$@"
-        elif [ -n "$(declare -f _command_not_found_handler)" ]; then
-            _command_not_found_handler "$@"
-        else
-            echo "zsh: command not found: $1" >&2
-            return 127
-        fi
-    }
-fi
+# vim: noet ci pi sts=0 sw=4 ts=4
 # === End: Mise ===
 
 # Compilation flags
@@ -135,3 +132,5 @@ eval "$(uv generate-shell-completion zsh)"
 ## [/Completion]
 export PATH="$PATH:/home/mzwallow/Development/ai/unsloth-llm/tmp/ngc-cli"
 export LOCAL_NIM_CACHE=~/.cache/nim
+
+[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
